Feature/make default calendar
divineDuckk/Modsen-DataPicker pull request #1
Opened 2024-08-04 11:46 UTC by divineDuckk

2024-08-05 06:57 UTC, ilyaAzarenko commented on src/components/Calendar/Header/index.tsx
> +import prev from '@/assets/prev.svg';
Попробуй использовать svg как компоненты 
https://www.npmjs.com/package/%40svgr/webpack

2024-08-05 07:00 UTC, ilyaAzarenko requested changes

2024-08-05 07:00 UTC, ilyaAzarenko commented on src/components/Calendar/index.tsx
> +                ${extraDay && styles.extraDay}
используй либу classnames

2024-08-05 07:00 UTC, ilyaAzarenko commented on src/components/PopUp/popup.module.css
> +  background-color: rgba(0, 0, 0, 0.2);
сделай тему

2024-08-05 07:00 UTC, ilyaAzarenko commented
date-holiday убери
date-fns можно оставить

2024-08-05 16:50 UTC, ilyaAzarenko requested changes

2024-08-05 16:50 UTC, ilyaAzarenko commented on src/components/Calendar/calendar.module.css
> +:root {
лучше сделать отдельный файл для переменных

2024-08-05 16:50 UTC, ilyaAzarenko commented on src/components/Calendar/index.tsx
> +              ? WEEKS_START_WITH_MONDAY.map(weekDay => (
{MONDAY: WEEKS_START_WITH_MONDAY, SUNDAY:WEEKS_START_WITH_SUNDAY }[weekStartDay]

2024-08-05 16:50 UTC, ilyaAzarenko commented on src/constants/index.ts
> +export const DEFAULT_START_YEAR = 2003;
вот это лучше чтобы пропсами прилетало, держи в уме, что ты пишешь либу, и по идее её должно быть возможно всячески конфигурировать

2024-08-05 16:50 UTC, ilyaAzarenko commented on src/utils/functions/getDays.ts
> +  for (let i = 0; i < daysLength; i++) {
в js принято использовать foreEach

2024-08-06 09:18 UTC, ilyaAzarenko000 commented on src/utils/functions/getDays.ts
>    const lastExtraPos = 7 - (days.length % 7);
7 - magic numbers, в константы тут

2024-08-06 09:27 UTC, ilyaAzarenko000 approved these changes

2024-08-06 09:28 UTC, ilyaAzarenko approved these changes

2024-08-06 09:28 UTC, merged